backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index",
            }
          - { label: Background Image, name: backgroundimage, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Sub-Headline, name: subheadline, widget: string }
          - { label: Intro, name: intro, widget: text }
          - { label: Body Text, name: bodytext, widget: text }
          - { label: Profile Image, name: profileimage, widget: image }
      - label: "Thank You Page"
        name: "thank-you"
        file: "content/thank-you.md"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "thank-you",
            }
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Outtro, name: outtro, widget: text }
          - { label: Profile Image, name: profileimage, widget: image }
