backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Landing Page"
        name: "landing-page"
        file: "content/landing-page.md"
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: landing-page,
            }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Sub-Headline, name: subHeadline, widget: string }
          - { label: Introduction, name: introduction, widget: string }
          - { label: Call To Action, name: callToAction, widget: string }
          - { label: Body Text, name: body, widget: markdown }
          - { label: Profile Image, name: profileImage, widget: image }
      - label: "Thank You Page"
        name: "thank-you"
        file: "content/thank-you.md"
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: thank-you-page,
            }
          - { label: Title, name: title, widget: string }
          - { label: Headline, name: headline, widget: string }
          - { label: Outtro, name: outtro, widget: string }
          - { label: Profile Image, name: profileImage, widget: image }
